spring:
  application:
    name: music-web

server:
  contextPath: /music-web

management:
  security:
    enabled: false

security:
  user:
    name: admin
    password: password
  oauth2:
    client:
      client-id: devApp
      client-secret: devAppSecret
      access-token-uri: http://localhost:3300/auth/oauth/token
      grant-type: client_credentials
    resource.user-info-uri: http://localhost:3300/auth/user
  auth:
      id: devOAuth
      client:
        id: devApp
        secret: devAppSecret
    grant:
      type: client_credentials
    token:
      url: http://localhost:3300/auth/oauth/token
