spring:
  application:
    name: music-repository
  security:
    user:
      name: admin
      password: password
  jpa:
    hibernate:
      ddl-auto: validate
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
  show-sql: true

server:
  servlet:
    context-path: /music-repository

security:
  oauth2:
    client:
      client-id: devApp
      client-secret: devAppSecret
      access-token-uri: http://localhost:3300/auth/oauth/token
      grant-type: client_credentials
    resource.user-info-uri: http://localhost:3300/auth/user
