spring:
  application:
    name: music-service
  security:
    user:
      name: admin
      password: password

server:
  servlet:
    context-path: /music-service

security:
  oauth2:
    client:
      client-id: devApp
      client-secret: devAppSecret
      access-token-uri: http://localhost:3300/auth/oauth/token
      grant-type: client_credentials
    resource.user-info-uri: http://localhost:3300/auth/user
  auth:
    id: devOAuth
    client:
     id: devApp
     secret: devAppSecret
    grant:
      type: client_credentials
    token:
      url: http://localhost:3300/auth/oauth/token

music:
  repository:
    url: http://music-repository/music-repository